/*
 * embedded_loader.c — In-memory Android library loader.
 *
 * Lifecycle:
 *   1. Load libhybris-core.so from its embedded memfd → get android_dlopen/dlsym.
 *   2. Walk embedded_libs[]: for each entry write to a memfd, call
 *      android_dlopen("/proc/self/fd/N", RTLD_NOW | RTLD_GLOBAL).
 *      The Android linker registers each library by its ELF SONAME; subsequent
 *      android_dlopen("libstoreservicescore.so") returns the preloaded handle.
 *   3. Callers use embedded_dlopen() / embedded_dlsym() just like the old
 *      android_dlopen / android_dlsym, but without a live rootfs directory.
 *
 * All memfds are kept open for the lifetime of the process (the mapping is
 * backed by the fd; closing it unmaps the library).  embedded_loader_shutdown()
 * closes them.
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <stdint.h>
#include <pthread.h>

#include "embedded_loader.h"

/* ── Types mirrored from libhybris-core.so exports ──────────────────────────*/

typedef void *(*android_dlopen_fn)(const char *filename, int flags);
typedef void *(*android_dlsym_fn)(void *handle, const char *symbol);
typedef int   (*android_dlclose_fn)(void *handle);
typedef void  (*android_update_ld_fn)(const char *path);
typedef int   (*android_init_ns_fn)(const char *shared_libs, const char *lib_dir);

/* ── Module state ────────────────────────────────────────────────────────────*/

static struct {
    pthread_mutex_t lock;
    int             initialized;

    /* Linux host: libhybris-core.so */
    void           *hybris_handle;
    int             hybris_memfd;

    android_dlopen_fn  android_dlopen;
    android_dlsym_fn   android_dlsym;
    android_dlclose_fn android_dlclose;
    android_update_ld_fn android_update_ld;
    android_init_ns_fn   android_init_ns;

    /* Per-lib memfds — kept open so the Android linker mapping stays valid */
    int    lib_memfds[128];
    size_t lib_memfd_count;

    char last_error[512];
} g_el = {
    .lock          = PTHREAD_MUTEX_INITIALIZER,
    .hybris_memfd  = -1,
};

/* ── Embedded hybris-core image ─────────────────────────────────────────────*/

/* Defined in embedded_blobs/libhybris-core.so.S (generated by Makefile) */
extern const uint8_t  libhybris_core_so_data[];
extern const uint64_t libhybris_core_so_size;

/* ── Internal helpers ────────────────────────────────────────────────────────*/

static int write_memfd(const char *name, const uint8_t *data, uint64_t size)
{
    int fd = memfd_create(name, MFD_CLOEXEC);
    if (fd < 0) {
        snprintf(g_el.last_error, sizeof(g_el.last_error),
                 "memfd_create(%s): %s", name, strerror(errno));
        return -1;
    }

    const uint8_t *p = data;
    uint64_t       remaining = size;
    while (remaining > 0) {
        ssize_t written = write(fd, p, remaining);
        if (written < 0) {
            if (errno == EINTR) continue;
            snprintf(g_el.last_error, sizeof(g_el.last_error),
                     "write memfd(%s): %s", name, strerror(errno));
            close(fd);
            return -1;
        }
        p         += (size_t)written;
        remaining -= (size_t)written;
    }
    return fd;
}

/* ── Public API ──────────────────────────────────────────────────────────────*/

int embedded_loader_init(void)
{
    pthread_mutex_lock(&g_el.lock);
    if (g_el.initialized) { pthread_mutex_unlock(&g_el.lock); return 0; }

    /* ── Step 1: load libhybris-core.so from its embedded image ── */
    int hfd = write_memfd("libhybris-core.so",
                          libhybris_core_so_data,
                          libhybris_core_so_size);
    if (hfd < 0) { pthread_mutex_unlock(&g_el.lock); return -1; }

    char hpath[64];
    snprintf(hpath, sizeof(hpath), "/proc/self/fd/%d", hfd);
    g_el.hybris_handle = dlopen(hpath, RTLD_NOW | RTLD_GLOBAL);
    if (!g_el.hybris_handle) {
        snprintf(g_el.last_error, sizeof(g_el.last_error),
                 "dlopen(libhybris-core.so): %s", dlerror());
        close(hfd);
        pthread_mutex_unlock(&g_el.lock);
        return -1;
    }
    g_el.hybris_memfd = hfd;

    g_el.android_dlopen    = (android_dlopen_fn)   dlsym(g_el.hybris_handle, "android_dlopen");
    g_el.android_dlsym     = (android_dlsym_fn)    dlsym(g_el.hybris_handle, "android_dlsym");
    g_el.android_dlclose   = (android_dlclose_fn)  dlsym(g_el.hybris_handle, "android_dlclose");
    g_el.android_update_ld = (android_update_ld_fn)dlsym(g_el.hybris_handle, "android_update_LD_LIBRARY_PATH");
    g_el.android_init_ns   = (android_init_ns_fn)  dlsym(g_el.hybris_handle, "android_init_anonymous_namespace");

    if (!g_el.android_dlopen || !g_el.android_dlsym) {
        snprintf(g_el.last_error, sizeof(g_el.last_error),
                 "android_dlopen/dlsym not found in libhybris-core.so");
        dlclose(g_el.hybris_handle); g_el.hybris_handle = NULL;
        close(hfd); g_el.hybris_memfd = -1;
        pthread_mutex_unlock(&g_el.lock);
        return -1;
    }

    fprintf(stderr, "[embedded_loader] libhybris-core.so loaded from memfd\n");

    /* ── Step 2: preload every embedded Android lib via its own memfd ──
     * Opt-in (AML_EMBED_LIBS=1): by default libs load from HYBRIS_LD_LIBRARY_PATH
     * by their real paths, as the reference wrapper does.  Memfd-loaded libs
     * break FairPlay code that locates files relative to its own library path
     * (the lease request crashes on a NULL FilePath-backed Data). */
    const char *embed_libs = getenv("AML_EMBED_LIBS");
    for (uint64_t i = 0; i < num_embedded_libs && embed_libs && embed_libs[0] == '1'; i++) {
        const embedded_lib_entry_t *entry = &embedded_libs[i];

        int fd = write_memfd(entry->name, entry->data, entry->size);
        if (fd < 0) {
            /* Log but continue — a missing optional lib shouldn't abort init */
            fprintf(stderr, "[embedded_loader] memfd(%s) failed: %s\n",
                    entry->name, g_el.last_error);
            continue;
        }

        char path[64];
        snprintf(path, sizeof(path), "/proc/self/fd/%d", fd);

        void *handle = g_el.android_dlopen(path, 0x102 /* RTLD_NOW | RTLD_GLOBAL */);
        if (!handle) {
            fprintf(stderr, "[embedded_loader] android_dlopen(%s) failed\n", entry->name);
            close(fd);
            continue;
        }

        /* Keep fd open — the Android linker mapping is backed by it */
        if (g_el.lib_memfd_count < 128) {
            g_el.lib_memfds[g_el.lib_memfd_count++] = fd;
        } else {
            /* Overflow safety: keep fd open anyway via /proc/self/fd */
            /* (won't happen with our ~25 libs) */
        }
        fprintf(stderr, "[embedded_loader] loaded %s\n", entry->name);
    }

    g_el.initialized = 1;
    pthread_mutex_unlock(&g_el.lock);
    return 0;
}

void *embedded_dlopen(const char *name, int flags)
{
    if (!g_el.initialized || !g_el.android_dlopen) {
        snprintf(g_el.last_error, sizeof(g_el.last_error), "not initialized");
        return NULL;
    }
    /* The lib is already preloaded; android_dlopen returns the cached handle */
    return g_el.android_dlopen(name, flags);
}

void *embedded_dlsym(const char *symbol)
{
    if (!g_el.initialized || !g_el.android_dlsym) {
        snprintf(g_el.last_error, sizeof(g_el.last_error), "not initialized");
        return NULL;
    }
    return g_el.android_dlsym(NULL, symbol);
}

void *embedded_dlsym_in(void *handle, const char *symbol)
{
    if (!g_el.initialized || !g_el.android_dlsym) {
        snprintf(g_el.last_error, sizeof(g_el.last_error), "not initialized");
        return NULL;
    }
    return g_el.android_dlsym(handle, symbol);
}

const char *embedded_dlerror(void)
{
    return g_el.last_error[0] ? g_el.last_error : NULL;
}

void embedded_loader_shutdown(void)
{
    pthread_mutex_lock(&g_el.lock);
    if (!g_el.initialized) { pthread_mutex_unlock(&g_el.lock); return; }

    /* Close all per-lib memfds */
    for (size_t i = 0; i < g_el.lib_memfd_count; i++) {
        if (g_el.lib_memfds[i] >= 0) {
            close(g_el.lib_memfds[i]);
            g_el.lib_memfds[i] = -1;
        }
    }
    g_el.lib_memfd_count = 0;

    /* Unload hybris */
    if (g_el.hybris_handle) {
        dlclose(g_el.hybris_handle);
        g_el.hybris_handle = NULL;
    }
    if (g_el.hybris_memfd >= 0) {
        close(g_el.hybris_memfd);
        g_el.hybris_memfd = -1;
    }

    g_el.initialized    = 0;
    g_el.android_dlopen = NULL;
    g_el.android_dlsym  = NULL;
    pthread_mutex_unlock(&g_el.lock);
}
