/*
 * embedded_loader.h — In-memory Android library loader.
 *
 * Embeds libhybris-core.so and all Android .so dependencies as binary data
 * in the final shared library.  At runtime each library is written to an
 * anonymous memfd and loaded via dlopen(/proc/self/fd/N), so the process
 * never needs an on-disk rootfs/system/lib64/ directory.
 *
 * Build step (Makefile) generates embedded_blobs/<libname.so>.S for each lib
 * via xxd, assembles them into .o files, and links them in.  The
 * embedded_symtable.S file provides the `embedded_libs[]` array and
 * `num_embedded_libs` count that this loader iterates over.
 */
#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Per-library descriptor ─────────────────────────────────────────────────*/

typedef struct {
    const uint8_t *data;  /* Pointer to embedded binary data */
    uint64_t        size;  /* Exact byte count of that data */
    const char     *name;  /* Library filename, e.g. "libstoreservicescore.so" */
} embedded_lib_entry_t;

/* Symtable and count — defined in embedded_symtable.S (generated by Makefile) */
extern const embedded_lib_entry_t embedded_libs[];
extern const uint64_t             num_embedded_libs;

/* ── Loader API ─────────────────────────────────────────────────────────────*/

/*
 * embedded_loader_init() — load all embedded Android libraries into the
 * hybris namespace via anonymous memfds.
 *
 * Must be called before any android_dlopen/dlsym calls.
 * Returns 0 on success, -1 on failure (check embedded_dlerror()).
 */
int embedded_loader_init(void);

/*
 * embedded_dlopen() — open a library that was preloaded by embedded_loader_init().
 * Returns the handle from android_dlopen, or NULL on failure.
 * flags: same as android_dlopen (RTLD_NOW | RTLD_GLOBAL etc.)
 */
void *embedded_dlopen(const char *name, int flags);

/*
 * embedded_dlsym() — look up a symbol across all loaded Android libraries.
 * Equivalent to android_dlsym(NULL, symbol) — searches all loaded libs.
 */
void *embedded_dlsym(const char *symbol);

/*
 * embedded_dlsym_in() — look up a symbol in a specific handle.
 */
void *embedded_dlsym_in(void *handle, const char *symbol);

/* embedded_dlerror() — return last error string */
const char *embedded_dlerror(void);

/* embedded_loader_shutdown() — close all memfds, unload hybris */
void embedded_loader_shutdown(void);

#ifdef __cplusplus
}
#endif
