// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadCredentials() {
  return window['go']['main']['App']['LoadCredentials']();
}

export function StartStreamPlayback(arg1) {
  return window['go']['main']['App']['StartStreamPlayback'](arg1);
}

export function StopStreamPlayback() {
  return window['go']['main']['App']['StopStreamPlayback']();
}

export function StoreCredentials(arg1) {
  return window['go']['main']['App']['StoreCredentials'](arg1);
}

export function WrapperLogs() {
  return window['go']['main']['App']['WrapperLogs']();
}

export function WrapperSendInput(arg1) {
  return window['go']['main']['App']['WrapperSendInput'](arg1);
}
