// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAppleIDCredentials():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function HasAppleIDCredentials():Promise<boolean>;

export function LoadAppleIDCredentials():Promise<string>;

export function LoadCredentials():Promise<string>;

export function StoreAppleIDCredentials(arg1:string,arg2:string):Promise<void>;

export function StoreCredentials(arg1:string):Promise<void>;
