// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function LoadCredentials():Promise<string>;

export function StartStreamPlayback(arg1:string):Promise<void>;

export function StopStreamPlayback():Promise<void>;

export function StoreCredentials(arg1:string):Promise<void>;

export function WrapperLogs():Promise<Array<string>>;

export function WrapperSendInput(arg1:string):Promise<void>;
