// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAppleIDCredentials() {
  return window['go']['main']['App']['ClearAppleIDCredentials']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasAppleIDCredentials() {
  return window['go']['main']['App']['HasAppleIDCredentials']();
}

export function LoadAppleIDCredentials() {
  return window['go']['main']['App']['LoadAppleIDCredentials']();
}

export function LoadCredentials() {
  return window['go']['main']['App']['LoadCredentials']();
}

export function StartStreamPlayback(arg1) {
  return window['go']['main']['App']['StartStreamPlayback'](arg1);
}

export function StopStreamPlayback() {
  return window['go']['main']['App']['StopStreamPlayback']();
}

export function StoreAppleIDCredentials(arg1, arg2) {
  return window['go']['main']['App']['StoreAppleIDCredentials'](arg1, arg2);
}

export function StoreCredentials(arg1) {
  return window['go']['main']['App']['StoreCredentials'](arg1);
}
